apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: web-hugo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - beta.safespring.se
      secretName: tls-beta-safespring-se
    - hosts:
        - beta.safespring.eu
      secretName: tls-beta-safespring-eu
    - hosts:
        - beta.safespring.no
      secretName: tls-beta-safespring-no
    - hosts:
        - beta.safespring.dk
      secretName: tls-beta-safespring-dk
  rules:
    - host: beta.safespring.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8081
    - host: beta.safespring.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8082
    - host: beta.safespring.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8083
    - host: beta.safespring.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8084