apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: beta.safespring.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-hugo
            port:
              number: 8081
  - host: beta.safespring.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-hugo
            port:
              number: 8082
  - host: beta.safespring.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-hugo
            port:
              number: 8083
  - host: beta.safespring.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-hugo
            port:
              number: 8084