apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-beta
namePrefix: beta-
labels:
  - pairs:
      env: beta
resources:
  - ../../base
  - ingress.yaml
replicas:
  - name: web
    count: 2
images:
  - name: ghcr.io/safespring/web
    newTag: beta
