baseURL = "https://www.safespring.com/"
languageCode = "sv"
title = "Empowering European Innovation"
author = "Safespring"
copyright = "2025 Safespring"

# Pagination
paginate = 10
paginatePath = "blog"

[params]
  mainSections = ['blogg', 'webinar', 'whitepaper', 'solution-brief']

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'igor'
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.extensions]
    footnote = true

[blackfriday]
fractions = false

[minify]
  minifyOutput = true
