apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hugo-web-beta
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=ghcr.io/safespring/web:beta
    argocd-image-updater.argoproj.io/web.update-strategy: digest
spec:
  project: default

  source:
    repoURL: https://github.com/safespring/web.git
    targetRevision: kube-dev
    path: deploy/overlays/beta

  destination:
    server: https://kubernetes.default.svc
    namespace: web-hugo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
