apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - web-nginx-conf.yaml
configMapGenerator:
  - name: content-revision
    files:
      - ../../.git/index
commonLabels:
  app.kubernetes.io/name: safespring-web
