apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/safespring/web
    newTag: beta
labels:
  - pairs:
      app.kubernetes.io/name: safespring-web
