apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web-hugo
spec:
  selector:
    app: web
  ports:
    - name: sv
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: en
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: nb
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: da
      port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP
